# Generated by Django 4.0.5 on 2022-06-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_ratings.media')),
            ],
        ),
        migrations.CreateModel(
            name='IMDbScores',
            fields=[
                ('mediascore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media_ratings.mediascore')),
                ('imdb_score', models.FloatField(blank=True)),
            ],
            bases=('media_ratings.mediascore',),
        ),
        migrations.CreateModel(
            name='RottentomatoesScores',
            fields=[
                ('mediascore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media_ratings.mediascore')),
                ('tomatometer_score', models.IntegerField(blank=True)),
                ('audience_score', models.IntegerField(blank=True)),
            ],
            bases=('media_ratings.mediascore',),
        ),
        migrations.CreateModel(
            name='TV_Series',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media_ratings.media')),
                ('num_seasons', models.IntegerField(blank=True, default=1)),
                ('num_eps_per_season', models.IntegerField(blank=True, default=1)),
                ('num_eps', models.IntegerField(blank=True, default=1)),
            ],
            bases=('media_ratings.media',),
        ),
    ]
